# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fasterRndWalk <- function(gSetIdx, geneRanking, j, Ra) {
    .Call('_GSVA_fasterRndWalk', PACKAGE = 'GSVA', gSetIdx, geneRanking, j, Ra)
}

